---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Informations sur la distribution
      vars:
        msg: |
            {{ ansible_distribution_file_variety }} {{ ansible_distribution_version }}
            python: {{ discovered_interpreter_python }}
            python version: {{ ansible_python_version }}
      debug:
        msg: "{{ msg.split('\n') }}"